repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(corpus/|local_data/)
  - id: end-of-file-fixer
    exclude: ^(corpus/|local_data/)
  - id: check-ast
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: debug-statements

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.191'
  hooks:
    - id: ruff
      args: ["--force-exclude"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    exclude: ^(corpus/|local_data/)
